// <auto-generated />

#nullable disable

using GPM.Product.Data;

namespace GPM.Product.Data.Migrations
{
    [DbContext(typeof(CubeIntersectorDBContext))]
    [Migration("20230301162615_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPM.Product.Data.Entity.CubeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TDCE_ID")
                        .HasColumnOrder(0);

                    b.Property<float>("Depth")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_DEPTH")
                        .HasColumnOrder(6);

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_HEIGHT")
                        .HasColumnOrder(5);

                    b.Property<float>("Width")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_WIDTH")
                        .HasColumnOrder(4);

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_X")
                        .HasColumnOrder(1);

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_Y")
                        .HasColumnOrder(2);

                    b.Property<float>("Z")
                        .HasColumnType("real")
                        .HasColumnName("TDCE_Z")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TD_CUBE");

                    b.HasData(
                        new
                        {
                            Id = "test1",
                            Depth = 5f,
                            Height = 4f,
                            Width = 3f,
                            X = 0f,
                            Y = 1f,
                            Z = 2f
                        },
                        new
                        {
                            Id = "test2",
                            Depth = 6f,
                            Height = 5f,
                            Width = 4f,
                            X = 1f,
                            Y = 2f,
                            Z = 3f
                        },
                        new
                        {
                            Id = "test3",
                            Depth = 7f,
                            Height = 6f,
                            Width = 5f,
                            X = 2f,
                            Y = 3f,
                            Z = 4f
                        },
                        new
                        {
                            Id = "test4",
                            Depth = 8f,
                            Height = 7f,
                            Width = 6f,
                            X = 3f,
                            Y = 4f,
                            Z = 5f
                        },
                        new
                        {
                            Id = "test5",
                            Depth = 8f,
                            Height = 8f,
                            Width = 7f,
                            X = 4f,
                            Y = 5f,
                            Z = 6f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
